metabomatch/news/models.py
from datetime import datetime

from metabomatch.extensions import db
from metabomatch.flaskbb.utils.helpers import slugify

import markdown2

class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False)
    creation_date = db.Column(db.DateTime, default=datetime.utcnow())

    content = db.Column(db.Text, nullable=False)

    def __init__(self, title, content):
        self.title = title
        self.content = content

    @property
    def slug(self):
        return slugify(self.title)

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def to_html(self):
        return markdown2.markdown(self.content)

metabomatch/jobs/forms.py
from datetime import datetime

from flask.ext.wtf import Form
from flask.ext.login import current_user
from metabomatch.extensions import db
from metabomatch.jobs.models import Job, JobTags

from wtforms import StringField, TextAreaField, DateField
from wtforms.validators import DataRequired, URL, Optional, Email


class JobForm(Form):
    company = StringField('company*', validators=[DataRequired(message='missing company name')])

    #fixed ace was empty if validator fails that lead to a TODO
    company_url = StringField('company link', validators=[Optional()])  # , URL(message='not a valid url')])
    workplace = StringField('workplace*', validators=[DataRequired(message='workplace is missing')])

    name = StringField('name*', validators=[DataRequired(message='missing job name')])

    description = TextAreaField('description*',
                                validators=[DataRequired(message='missing job description')],
                                description='Use markdown to write your job offer')

    motivation = TextAreaField('motivation', validators=[Optional()],
                               description='Describe in one sentence why programmers should join your company')

    apply_date_limit = DateField('apply limit date', format='%d-%m-%Y', validators=[Optional()])
    contact_email = StringField('contact_email*',
                                validators=[DataRequired(message="missing contact email"),
                                            Email(message="not a valid email")])

    job_tags = StringField('tags', description='programming languages, expertise...', default='')

    def save(self, user_id=None):

        job = Job(self.company.data, self.company_url.data)
        job.name = self.name.data

        job.workplace = self.workplace.data

        job.description = self.description.data
        job.motivation = self.motivation.data
        job.apply_date_limit = self.apply_date_limit.data
        job.contact_email = self.contact_email.data

        job.user_id = current_user.id or user_id
        job.is_closed = False
        #tags
        tags = self.job_tags.data.split(",")
        l = []
        for tag in tags:
            t = db.session.query(JobTags).get(tag)
            if t is None:
                new_tag = JobTags(tag).save()
                l.append(new_tag)
            else:
                l.append(t)
        job.job_tags = l

        #return instance object
        return job.save()

metabomatch/flaskbb/__init__.py
# -*- coding: utf-8 -*-
"""
    flaskbb
    ~~~~~~~~~~~~~~~~~~~~

    FlaskBB is a forum software written in python using the
    microframework Flask.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""

__version__ = '0.1-dev'

#from flaskbb.app import create_app

metabomatch/flaskbb/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import datetime

from flask import (Blueprint, redirect, url_for, current_app,
                   request, flash)
from flask.ext.login import login_required, current_user
from metabomatch.email import send_reply_notification

from metabomatch.extensions import db
from metabomatch.flaskbb.utils.settings import flaskbb_config
from metabomatch.flaskbb.utils.helpers import (get_online_users, time_diff, render_template,
                                               format_quote)
from metabomatch.flaskbb.utils.permissions import (can_post_reply, can_post_topic,
                                                   can_delete_topic, can_delete_post,
                                                   can_edit_post, can_moderate)
from metabomatch.flaskbb.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                              TopicsRead)
from metabomatch.flaskbb.forum.forms import (QuickreplyForm, ReplyForm, NewTopicForm,
                                             ReportForm, UserSearchForm, SearchPageForm)
from metabomatch.user.models import User

forum = Blueprint("forum", __name__, template_folder="../../templates")


@forum.route("/")
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()

    # Check if we use redis or not
    if not current_app.config["REDIS_ENABLED"]:
        online_users = User.query.filter(User.lastseen >= time_diff()).count()

        # Because we do not have server side sessions, we cannot check if there
        # are online guests
        online_guests = None
    else:
        online_users = len(get_online_users())
        online_guests = len(get_online_users(guest=True))

    return render_template("forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user,
                           online_users=online_users,
                           online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
def view_category(category_id, slug=None):
    category, forums = Category.\
        get_forums(category_id=category_id, user=current_user)

    return render_template("forum/category.html", forums=forums,
                           category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id, user=current_user)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(forum_id=forum_instance.id, user=current_user, page=page,
                              per_page=flaskbb_config["TOPICS_PER_PAGE"])

    return render_template("forum/forum.html", forum=forum_instance, topics=topics,
                           forumsread=forumsread,)


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    topic = Topic.query.filter_by(id=topic_id).first()
    posts = Post.query.filter_by(topic_id=topic.id).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Count the topic views
    topic.views += 1

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated():
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)
    topic.save()

    form = None

    if not topic.locked \
        and not topic.forum.locked \
        and can_post_reply(user=current_user,
                           forum=topic.forum):

            form = QuickreplyForm()
            if form.validate_on_submit():
                post = form.save(current_user, topic)

                involved_users = User.query.filter(Post.topic_id == topic.id, User.id == Post.user_id).all()
                recipients = list(set(involved_users) - {current_user})
                if recipients:
                    send_reply_notification(recipients, topic_title=topic.title,
                                            link="http://www.metabomatch/topic/{}".format(topic.slug))
                    return view_post(post.id)

    return render_template("forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    count = post.topic.post_count
    page = count / flaskbb_config["POSTS_PER_PAGE"]

    if count > flaskbb_config["POSTS_PER_PAGE"]:
        page += 1
    else:
        page = 1

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])  # @login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if forum_instance.locked:
        flash("This forum is locked; you cannot submit new topics or posts.",
              "danger")
        return redirect(forum_instance.url)

    if not can_post_topic(user=current_user, forum=forum_instance):
        flash("You do not have the permissions to create a new topic.",
              "danger")
        return redirect(forum_instance.url)

    form = NewTopicForm()
    if request.method == "POST":
        # if "preview" in request.form and form.validate():
        #     return render_template(
        #         "forum/new_topic.html", forum=forum_instance,
        #         form=form, preview=form.content.data
        #     )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)

            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template("forum/new_topic.html", forum=forum, form=form)


@forum.route("/topic/<int:topic_id>/delete")
@forum.route("/topic/<int:topic_id>-<slug>/delete")
@login_required
def delete_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_delete_topic(user=current_user, forum=topic.forum,
                            post_user_id=topic.first_post.user_id):

        flash("You do not have the permissions to delete the topic", "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock")
@forum.route("/topic/<int:topic_id>-<slug>/lock")
@login_required
def lock_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk lock

    if not can_moderate(user=current_user, forum=topic.forum):
        flash("You do not have the permissions to lock this topic", "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock")
@forum.route("/topic/<int:topic_id>-<slug>/unlock")
@login_required
def unlock_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk unlock

    # Unlock is basically the same as lock
    if not can_moderate(user=current_user, forum=topic.forum):
        flash("Yo do not have the permissions to unlock this topic", "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/move/<int:forum_id>")
@forum.route("/topic/<int:topic_id>-<topic_slug>/move/<int:forum_id>-<forum_slug>")
@login_required
def move_topic(topic_id, forum_id, topic_slug=None, forum_slug=None):
    forum = Forum.query.filter_by(id=forum_id).first_or_404()
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk move

    if not can_moderate(user=current_user, forum=topic.forum):
        flash("You do not have the permissions to move this topic", "danger")
        return redirect(forum.url)

    if not topic.move(forum):
        flash("Could not move the topic to forum %s" % forum.title, "danger")
        return redirect(topic.url)

    flash("Topic was moved to forum %s" % forum.title, "success")
    return redirect(topic.url)


@forum.route("/topic/<int:old_id>/merge/<int:new_id>")
@forum.route("/topic/<int:old_id>-<old_slug>/merge/<int:new_id>-<new_slug>")
@login_required
def merge_topic(old_id, new_id, old_slug=None, new_slug=None):
    old_topic = Topic.query.filter_by(id=old_id).first_or_404()
    new_topic = Topic.query.filter_by(id=new_id).first_or_404()

    # TODO: Bulk merge

    if not can_moderate(user=current_user, forum=old_topic.forum):
        flash("Yo do not have the permissions to merge this topic", "danger")
        return redirect(old_topic.url)

metabomatch/flaskbb/plugins/__init__.py
from flask.ext.plugins import Plugin
from flask import current_app

from metabomatch.flaskbb.management.models import SettingsGroup


class FlaskBBPlugin(Plugin):

    #: This is the :class:`SettingsGroup` key - if your the plugin needs to
    #: install additional things you must set it, else it won't install
    #: anything.
    settings_key = None

    @property
    def installable(self):
        """Is ``True`` if the Plugin can be installed."""
        if self.settings_key is not None:
            return True
        return False

    @property
    def uninstallable(self):
        """Is ``True`` if the Plugin can be uninstalled."""
        if self.installable:
            group = SettingsGroup.query.filter_by(key=self.settings_key).first()
            if group and len(group.settings.all()) > 0:
                return True
            return False
        return False

        # Some helpers
    def register_blueprint(self, blueprint, **kwargs):
        """Registers a blueprint.

        :param blueprint: The blueprint which should be registered.
        """
        current_app.register_blueprint(blueprint, **kwargs)

    def create_table(self, model, db):
        """Creates the relation for the model

        :param model: The Model which should be created
        :param db: The database instance.
        """
        if not model.__table__.exists(bind=db.engine):
            model.__table__.create(bind=db.engine)

    def drop_table(self, model, db):
        """Drops the relation for the bounded model.

        :param model: The model on which the table is bound.
        :param db: The database instance.
        """
        model.__table__.drop(bind=db.engine)

    def create_all_tables(self, models, db):
        """A interface for creating all models specified in ``models``.

        :param models: A list with models
        :param db: The database instance
        """
        for model in models:
            self.create_table(model, db)

    def drop_all_tables(self, models, db):
        """A interface for dropping all models specified in the
        variable ``models``.

        :param models: A list with models
        :param db: The database instance.
        """
        for model in models:
            self.drop_table(model, db)

metabomatch/flaskbb/plugins/portal/__init__.py
from flask.ext.plugins import connect_event

from metabomatch.flaskbb.plugins import FlaskBBPlugin
from metabomatch.flaskbb.utils.populate import (create_settings_from_fixture,
                                    delete_settings_from_fixture)
from metabomatch.flaskbb.forum.models import Forum

from .views import portal, inject_portal_link

__version__ = "0.1"
__plugin__ = "PortalPlugin"


def available_forums():
    forums = Forum.query.order_by(Forum.id.asc()).all()
    return [(forum.id, forum.title) for forum in forums]

fixture = (
    ('plugin_portal', {
        'name': "Portal Settings",
        "description": "Configure the portal",
        "settings": (
            ('plugin_portal_forum_ids', {
                'value':        [1],
                'value_type':   "selectmultiple",
                'name':         "Forum IDs",
                'description':  "The forum ids from which forums the posts should be displayed on the portal.",
                'extra': {"choices": available_forums, "coerce": int}
            }),
        ),
    }),
)


class PortalPlugin(FlaskBBPlugin):

    name = "Portal Plugin"

    description = ("This Plugin provides a simple portal for FlaskBB.")

    author = "sh4nks"

    license = "BSD"

    version = __version__

    settings_key = 'plugin_portal'

    def setup(self):
        self.register_blueprint(portal, url_prefix="/portal")
        connect_event("before-first-navigation-element", inject_portal_link)

    def install(self):
        create_settings_from_fixture(fixture)

    def uninstall(self):
        delete_settings_from_fixture(fixture)

metabomatch/templates/management/banned_users.html
{% set page_title = "Banned Users" %}
{% set active_management_user_nav=True %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme('macros.html') import render_pagination, render_field, group_field, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.users', "Manage Users") }}
        {{ navlink('management.banned_users', 'Banned Users') }}

        {% if current_user|is_admin %}
            {{ navlink('management.add_user', "Add User") }}
        {% endif %}
    </ul>
</div><!--/.col-md-3 -->

<div class="col-md-9">
    <legend>Banned Users</legend>

    <div class="pull-left" style="padding-bottom: 10px">
        {{ render_pagination(users, url_for('management.users')) }}
    </div>
    <div class="pull-right" style="padding-bottom: 10px">
        <form role="form" method="post">
            <div class="input-group">
                {{ search_form.hidden_tag() }}
                {{ group_field(search_form.search_query) }}
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th>Posts</th>
                <th>Date registered</th>
                <th>Group</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users.items %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td><a href="{{ url_for('user.profile', username=user.username) }}">{{ user.username }}</a></td>
                    <td>{{ user.post_count }}</td>
                    <td>{{ user.date_joined|format_date('%b %d %Y') }}</td>
                    <td>{{ user.primary_group.name }}</td>
                    <td>
                        {% if current_user|can_ban_user and user.permissions['banned'] %}
                            <a href="{{ url_for('management.unban_user', user_id = user.id) }}">Unban</a>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">
                        No users found matching your search query
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

metabomatch/templates/management/category_form.html
{% set page_title = title %}
{% set active_management_forum_nav=True %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme("macros.html") import horizontal_field, render_boolean_field, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.forums', "Manage Forums") }}
        {{ navlink('management.add_forum', "Add Forum") }}
        {{ navlink('management.add_category', "Add Category") }}
    </ul>
</div>

<div class="col-md-9">
    <form class="form-horizontal" role="form" method="post">
        {{ form.hidden_tag() }}
        <legend class="">{{ title }}</legend>
            {{ horizontal_field(form.title) }}
            {{ horizontal_field(form.description, rows=5, div_class="col-lg-9") }}

            {{ horizontal_field(form.position) }}

            <div class="form-group">
                <div class="col-lg-offset-0 col-lg-9">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
    </form>
</div>

{% endblock %}

metabomatch/templates/management/forum_form.html
{% set page_title = title %}
{% set active_management_forum_nav=True %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme("macros.html") import horizontal_field, render_boolean_field, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.forums', "Manage Forums") }}
        {{ navlink('management.add_forum', "Add Forum") }}
        {{ navlink('management.add_category', "Add Category") }}
    </ul>
</div>

<div class="col-md-9">
    <form class="form-horizontal" role="form" method="post">
        {{ form.hidden_tag() }}
        <legend class="">{{ title }}</legend>
            {{ horizontal_field(form.title) }}
            {{ horizontal_field(form.description, rows=5, div_class="col-lg-9") }}

            {{ horizontal_field(form.category) }}
            {{ horizontal_field(form.position) }}

            {{ horizontal_field(form.external) }}

            {{ horizontal_field(form.moderators) }}
            {{ render_boolean_field(form.show_moderators) }}

            {{ render_boolean_field(form.locked) }}

            <div class="form-group">
                <div class="col-lg-offset-0 col-lg-9">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
    </form>
</div>
{% endblock %}

metabomatch/templates/management/forums.html
{% set page_title = "Forums" %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme('macros.html') import render_pagination, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.forums', "Manage Forums") }}
        {{ navlink('management.add_forum', "Add Forum") }}
        {{ navlink('management.add_category', "Add Category") }}
    </ul>
</div>


<div class="col-md-9">
    <legend>Manage Forums</legend>

    {% for category in categories %}
    <table class="table table-bordered">
        <thead class="categoryhead">
            <tr>
                <td colspan="2">
                    <div><strong><a href="{{ url_for('forum.view_category', category_id=category.id) }}">{{ category.title }}</a></strong></div>
                </td>
                <td valign="top" align="center" style="white-space: nowrap">
                    <a href="{{ url_for('management.add_forum', category_id=category.id) }}">Add Forum</a> |
                    <a href="{{ url_for('management.edit_category', category_id = category.id) }}">Edit</a> |
                    <a href="{{ url_for('management.delete_category', category_id = category.id) }}">Delete</a>
                </td>
            </tr>
        </thead>
        <tbody class="forumbody">
            <tr class="forum_stats">
                <td colspan="2"><strong>Forum</strong></td>
                <td width="85" align="center" style="white-space: nowrap"><strong>Management</strong></td>
            </tr>

            {% for forum in category.forums %}
            <tr>
                <td align="center" valign="center" width="4%">

                </td>

                <td valign="top">
                    <strong><a href="{{ url_for('forum.view_forum', forum_id=forum.id) }}">{{ forum.title }}</a></strong>

                    <div class="forum-description">
                        {% autoescape false %}
                        {{ forum.description|markup }}
                        {% endautoescape %}
                    </div>
                </td>

                <td valign="top" align="center" style="white-space: nowrap">
                    <a href="{{ url_for('management.edit_forum', forum_id = forum.id) }}">Edit</a> |
                    <a href="{{ url_for('management.delete_forum', forum_id = forum.id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    {% endfor %}
</div>
{% endblock %}

metabomatch/templates/management/group_form.html
{% set page_title = title %}
{% set active_management_group_nav=True %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme("macros.html") import horizontal_field, render_boolean_field, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.groups', "Manage Groups") }}
        {{ navlink('management.add_group', "Add Group") }}
    </ul>
</div>

<div class="col-md-9">
    <form class="form-horizontal" role="form" method="post">
        {{ form.hidden_tag() }}
        <legend class="">{{ title }}</legend>
            {{ horizontal_field(form.name) }}
            {{ horizontal_field(form.description) }}

            {{ render_boolean_field(form.admin) }}
            {{ render_boolean_field(form.super_mod) }}


            {{ render_boolean_field(form.mod) }}
            {{ render_boolean_field(form.banned) }}
            {{ render_boolean_field(form.guest) }}

            {{ render_boolean_field(form.mod_edituser) }}
            {{ render_boolean_field(form.mod_banuser) }}

            {{ render_boolean_field(form.editpost) }}
            {{ render_boolean_field(form.deletepost) }}
            {{ render_boolean_field(form.deletetopic) }}
            {{ render_boolean_field(form.posttopic) }}
            {{ render_boolean_field(form.postreply) }}

            <div class="form-group">
                <div class="col-lg-offset-0 col-lg-9">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
    </form>
</div>
{% endblock %}

metabomatch/templates/management/groups.html
{% set page_title = "Groups" %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}
{% from theme('macros.html') import render_pagination, navlink with context %}

<div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
        {{ navlink('management.groups', "Manage Groups") }}
        {{ navlink('management.add_group', "Add Group") }}
    </ul>
</div>

<div class="col-md-9">
    <legend>Manage Groups</legend>

    <div class="pull-left" style="padding-bottom: 10px">
        {{ render_pagination(groups, url_for('management.groups')) }}
    </div>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Group Name</th>
                <th>Description</th>
                <th>Manage</th>
            </tr>
        </thead>
        <tbody>
            {% for group in groups.items %}
            <tr>
                <td>{{ group.id }}</td>
                <td><a href="#">{{ group.name }}</a></td>
                <td>{{ group.description }}</td>
                <td>
                    <a href="{{ url_for('management.edit_group', group_id = group.id) }}">Edit</a> |
                    <a href="{{ url_for('management.delete_group', group_id = group.id) }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

metabomatch/templates/management/management_layout.html
{% extends theme("layout.html") %}
{% block content %}
{%- from theme('macros.html') import navlink with context -%}

<div class="col-md-12" style="padding-bottom: 10px">
    <ul class="nav nav-tabs nav-justified">
    {{ navlink('management.overview', 'Overview') }}
    {{ navlink('management.users', 'Users', active=active_management_user_nav) }}
    {{ navlink('management.unread_reports', 'Reports', active=active_management_report_nav) }}

    {% if current_user|is_admin %}
        {{ navlink('management.settings', 'Settings') }}
        {{ navlink('management.groups', 'Groups', active=active_management_group_nav) }}
        {{ navlink('management.forums', 'Forums', active=active_management_forum_nav) }}
        {{ navlink('management.plugins', 'Plugins') }}
    {% endif %}
    </ul>
</div>

{% block management_content %}{% endblock %}

{% endblock %}

metabomatch/templates/management/overview.html
{% set page_title = "Overview" %}

{% extends theme("management/management_layout.html") %}
{% block management_content %}

<div class="col-md-12">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="4">Global Statistics</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>FlaskBB Version</b></td>
                <td>{{ flaskbb_version }}</td>
                <td><b>Posts</b></td>
                <td>{{ post_count }}</td>
            </tr>
            <tr>
                <td><b>Python Version</b></td>
                <td>{{ python_version }}</td>
                <td><b>Topics</b></td>
                <td>{{ topic_count }}</td>
            </tr>
            <tr>
                <td><b>Flask Version</b></td>
                <td>{{ flask_version }}</td>
                <td><b>Users</b></td>
                <td>{{ user_count }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}