metabomatch/news/models.py
from datetime import datetime

from metabomatch.extensions import db
from metabomatch.flaskbb.utils.helpers import slugify

import markdown2

class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False)
    creation_date = db.Column(db.DateTime, default=datetime.utcnow())

    content = db.Column(db.Text, nullable=False)

    def __init__(self, title, content):
        self.title = title
        self.content = content

    @property
    def slug(self):
        return slugify(self.title)

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def to_html(self):
        return markdown2.markdown(self.content)

metabomatch/jobs/forms.py
from datetime import datetime

from flask.ext.wtf import Form
from flask.ext.login import current_user
from metabomatch.extensions import db
from metabomatch.jobs.models import Job, JobTags

from wtforms import StringField, TextAreaField, DateField
from wtforms.validators import DataRequired, URL, Optional, Email


class JobForm(Form):
    company = StringField('company*', validators=[DataRequired(message='missing company name')])

    #fixed ace was empty if validator fails that lead to a TODO
    company_url = StringField('company link', validators=[Optional()])  # , URL(message='not a valid url')])
    workplace = StringField('workplace*', validators=[DataRequired(message='workplace is missing')])

    name = StringField('name*', validators=[DataRequired(message='missing job name')])

    description = TextAreaField('description*',
                                validators=[DataRequired(message='missing job description')],
                                description='Use markdown to write your job offer')

    motivation = TextAreaField('motivation', validators=[Optional()],
                               description='Describe in one sentence why programmers should join your company')

    apply_date_limit = DateField('apply limit date', format='%d-%m-%Y', validators=[Optional()])
    contact_email = StringField('contact_email*',
                                validators=[DataRequired(message="missing contact email"),
                                            Email(message="not a valid email")])

    job_tags = StringField('tags', description='programming languages, expertise...', default='')

    def save(self, user_id=None):

        job = Job(self.company.data, self.company_url.data)
        job.name = self.name.data

        job.workplace = self.workplace.data

        job.description = self.description.data
        job.motivation = self.motivation.data
        job.apply_date_limit = self.apply_date_limit.data
        job.contact_email = self.contact_email.data

        job.user_id = current_user.id or user_id
        job.is_closed = False
        #tags
        tags = self.job_tags.data.split(",")
        l = []
        for tag in tags:
            t = db.session.query(JobTags).get(tag)
            if t is None:
                new_tag = JobTags(tag).save()
                l.append(new_tag)
            else:
                l.append(t)
        job.job_tags = l

        #return instance object
        return job.save()

metabomatch/flaskbb/__init__.py
# -*- coding: utf-8 -*-
"""
    flaskbb
    ~~~~~~~~~~~~~~~~~~~~

    FlaskBB is a forum software written in python using the
    microframework Flask.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""

__version__ = '0.1-dev'

#from flaskbb.app import create_app

metabomatch/flaskbb/forum/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.forum.views
    ~~~~~~~~~~~~~~~~~~~~

    This module handles the forum logic like creating and viewing
    topics and posts.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
import datetime

from flask import (Blueprint, redirect, url_for, current_app,
                   request, flash)
from flask.ext.login import login_required, current_user
from metabomatch.email import send_reply_notification

from metabomatch.extensions import db
from metabomatch.flaskbb.utils.settings import flaskbb_config
from metabomatch.flaskbb.utils.helpers import (get_online_users, time_diff, render_template,
                                               format_quote)
from metabomatch.flaskbb.utils.permissions import (can_post_reply, can_post_topic,
                                                   can_delete_topic, can_delete_post,
                                                   can_edit_post, can_moderate)
from metabomatch.flaskbb.forum.models import (Category, Forum, Topic, Post, ForumsRead,
                                              TopicsRead)
from metabomatch.flaskbb.forum.forms import (QuickreplyForm, ReplyForm, NewTopicForm,
                                             ReportForm, UserSearchForm, SearchPageForm)
from metabomatch.user.models import User

forum = Blueprint("forum", __name__, template_folder="../../templates")


@forum.route("/")
def index():
    categories = Category.get_all(user=current_user)

    # Fetch a few stats about the forum
    user_count = User.query.count()
    topic_count = Topic.query.count()
    post_count = Post.query.count()
    newest_user = User.query.order_by(User.id.desc()).first()

    # Check if we use redis or not
    if not current_app.config["REDIS_ENABLED"]:
        online_users = User.query.filter(User.lastseen >= time_diff()).count()

        # Because we do not have server side sessions, we cannot check if there
        # are online guests
        online_guests = None
    else:
        online_users = len(get_online_users())
        online_guests = len(get_online_users(guest=True))

    return render_template("forum/index.html",
                           categories=categories,
                           user_count=user_count,
                           topic_count=topic_count,
                           post_count=post_count,
                           newest_user=newest_user,
                           online_users=online_users,
                           online_guests=online_guests)


@forum.route("/category/<int:category_id>")
@forum.route("/category/<int:category_id>-<slug>")
def view_category(category_id, slug=None):
    category, forums = Category.\
        get_forums(category_id=category_id, user=current_user)

    return render_template("forum/category.html", forums=forums,
                           category=category)


@forum.route("/forum/<int:forum_id>")
@forum.route("/forum/<int:forum_id>-<slug>")
def view_forum(forum_id, slug=None):
    page = request.args.get('page', 1, type=int)

    forum_instance, forumsread = Forum.get_forum(forum_id=forum_id, user=current_user)

    if forum_instance.external:
        return redirect(forum_instance.external)

    topics = Forum.get_topics(forum_id=forum_instance.id, user=current_user, page=page,
                              per_page=flaskbb_config["TOPICS_PER_PAGE"])

    return render_template("forum/forum.html", forum=forum_instance, topics=topics,
                           forumsread=forumsread,)


@forum.route("/topic/<int:topic_id>", methods=["POST", "GET"])
@forum.route("/topic/<int:topic_id>-<slug>", methods=["POST", "GET"])
def view_topic(topic_id, slug=None):
    page = request.args.get('page', 1, type=int)

    topic = Topic.query.filter_by(id=topic_id).first()
    posts = Post.query.filter_by(topic_id=topic.id).\
        order_by(Post.id.asc()).\
        paginate(page, flaskbb_config['POSTS_PER_PAGE'], False)

    # Count the topic views
    topic.views += 1

    # Update the topicsread status if the user hasn't read it
    forumsread = None
    if current_user.is_authenticated():
        forumsread = ForumsRead.query.\
            filter_by(user_id=current_user.id,
                      forum_id=topic.forum.id).first()

    topic.update_read(current_user, topic.forum, forumsread)
    topic.save()

    form = None

    if not topic.locked \
        and not topic.forum.locked \
        and can_post_reply(user=current_user,
                           forum=topic.forum):

            form = QuickreplyForm()
            if form.validate_on_submit():
                post = form.save(current_user, topic)

                involved_users = User.query.filter(Post.topic_id == topic.id, User.id == Post.user_id).all()
                recipients = list(set(involved_users) - {current_user})
                if recipients:
                    send_reply_notification(recipients, topic_title=topic.title,
                                            link="http://www.metabomatch/topic/{}".format(topic.slug))
                    return view_post(post.id)

    return render_template("forum/topic.html", topic=topic, posts=posts,
                           last_seen=time_diff(), form=form)


@forum.route("/post/<int:post_id>")
def view_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    count = post.topic.post_count
    page = count / flaskbb_config["POSTS_PER_PAGE"]

    if count > flaskbb_config["POSTS_PER_PAGE"]:
        page += 1
    else:
        page = 1

    return redirect(post.topic.url + "?page=%d#pid%s" % (page, post.id))


@forum.route("/<int:forum_id>/topic/new", methods=["POST", "GET"])
@forum.route("/<int:forum_id>-<slug>/topic/new", methods=["POST", "GET"])  # @login_required
def new_topic(forum_id, slug=None):
    forum_instance = Forum.query.filter_by(id=forum_id).first_or_404()

    if forum_instance.locked:
        flash("This forum is locked; you cannot submit new topics or posts.",
              "danger")
        return redirect(forum_instance.url)

    if not can_post_topic(user=current_user, forum=forum_instance):
        flash("You do not have the permissions to create a new topic.",
              "danger")
        return redirect(forum_instance.url)

    form = NewTopicForm()
    if request.method == "POST":
        # if "preview" in request.form and form.validate():
        #     return render_template(
        #         "forum/new_topic.html", forum=forum_instance,
        #         form=form, preview=form.content.data
        #     )
        if "submit" in request.form and form.validate():
            topic = form.save(current_user, forum_instance)

            # redirect to the new topic
            return redirect(url_for('forum.view_topic', topic_id=topic.id))

    return render_template("forum/new_topic.html", forum=forum, form=form)


@forum.route("/topic/<int:topic_id>/delete")
@forum.route("/topic/<int:topic_id>-<slug>/delete")
@login_required
def delete_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    if not can_delete_topic(user=current_user, forum=topic.forum,
                            post_user_id=topic.first_post.user_id):

        flash("You do not have the permissions to delete the topic", "danger")
        return redirect(topic.forum.url)

    involved_users = User.query.filter(Post.topic_id == topic.id,
                                       User.id == Post.user_id).all()
    topic.delete(users=involved_users)
    return redirect(url_for("forum.view_forum", forum_id=topic.forum_id))


@forum.route("/topic/<int:topic_id>/lock")
@forum.route("/topic/<int:topic_id>-<slug>/lock")
@login_required
def lock_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk lock

    if not can_moderate(user=current_user, forum=topic.forum):
        flash("You do not have the permissions to lock this topic", "danger")
        return redirect(topic.url)

    topic.locked = True
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/unlock")
@forum.route("/topic/<int:topic_id>-<slug>/unlock")
@login_required
def unlock_topic(topic_id, slug=None):
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk unlock

    # Unlock is basically the same as lock
    if not can_moderate(user=current_user, forum=topic.forum):
        flash("Yo do not have the permissions to unlock this topic", "danger")
        return redirect(topic.url)

    topic.locked = False
    topic.save()
    return redirect(topic.url)


@forum.route("/topic/<int:topic_id>/move/<int:forum_id>")
@forum.route("/topic/<int:topic_id>-<topic_slug>/move/<int:forum_id>-<forum_slug>")
@login_required
def move_topic(topic_id, forum_id, topic_slug=None, forum_slug=None):
    forum = Forum.query.filter_by(id=forum_id).first_or_404()
    topic = Topic.query.filter_by(id=topic_id).first_or_404()

    # TODO: Bulk move

    if not can_moderate(user=current_user, forum=topic.forum):
        flash("You do not have the permissions to move this topic", "danger")
        return redirect(forum.url)

    if not topic.move(forum):
        flash("Could not move the topic to forum %s" % forum.title, "danger")
        return redirect(topic.url)

    flash("Topic was moved to forum %s" % forum.title, "success")
    return redirect(topic.url)


@forum.route("/topic/<int:old_id>/merge/<int:new_id>")
@forum.route("/topic/<int:old_id>-<old_slug>/merge/<int:new_id>-<new_slug>")
@login_required
def merge_topic(old_id, new_id, old_slug=None, new_slug=None):
    old_topic = Topic.query.filter_by(id=old_id).first_or_404()
    new_topic = Topic.query.filter_by(id=new_id).first_or_404()

    # TODO: Bulk merge

    if not can_moderate(user=current_user, forum=old_topic.forum):
        flash("Yo do not have the permissions to merge this topic", "danger")
        return redirect(old_topic.url)

metabomatch/flaskbb/plugins/__init__.py
from flask.ext.plugins import Plugin
from flask import current_app

from metabomatch.flaskbb.management.models import SettingsGroup


class FlaskBBPlugin(Plugin):

    #: This is the :class:`SettingsGroup` key - if your the plugin needs to
    #: install additional things you must set it, else it won't install
    #: anything.
    settings_key = None

    @property
    def installable(self):
        """Is ``True`` if the Plugin can be installed."""
        if self.settings_key is not None:
            return True
        return False

    @property
    def uninstallable(self):
        """Is ``True`` if the Plugin can be uninstalled."""
        if self.installable:
            group = SettingsGroup.query.filter_by(key=self.settings_key).first()
            if group and len(group.settings.all()) > 0:
                return True
            return False
        return False

        # Some helpers
    def register_blueprint(self, blueprint, **kwargs):
        """Registers a blueprint.

        :param blueprint: The blueprint which should be registered.
        """
        current_app.register_blueprint(blueprint, **kwargs)

    def create_table(self, model, db):
        """Creates the relation for the model

        :param model: The Model which should be created
        :param db: The database instance.
        """
        if not model.__table__.exists(bind=db.engine):
            model.__table__.create(bind=db.engine)

    def drop_table(self, model, db):
        """Drops the relation for the bounded model.

        :param model: The model on which the table is bound.
        :param db: The database instance.
        """
        model.__table__.drop(bind=db.engine)

    def create_all_tables(self, models, db):
        """A interface for creating all models specified in ``models``.

        :param models: A list with models
        :param db: The database instance
        """
        for model in models:
            self.create_table(model, db)

    def drop_all_tables(self, models, db):
        """A interface for dropping all models specified in the
        variable ``models``.

        :param models: A list with models
        :param db: The database instance.
        """
        for model in models:
            self.drop_table(model, db)

metabomatch/flaskbb/plugins/portal/__init__.py
from flask.ext.plugins import connect_event

from metabomatch.flaskbb.plugins import FlaskBBPlugin
from metabomatch.flaskbb.utils.populate import (create_settings_from_fixture,
                                    delete_settings_from_fixture)
from metabomatch.flaskbb.forum.models import Forum

from .views import portal, inject_portal_link

__version__ = "0.1"
__plugin__ = "PortalPlugin"


def available_forums():
    forums = Forum.query.order_by(Forum.id.asc()).all()
    return [(forum.id, forum.title) for forum in forums]

fixture = (
    ('plugin_portal', {
        'name': "Portal Settings",
        "description": "Configure the portal",
        "settings": (
            ('plugin_portal_forum_ids', {
                'value':        [1],
                'value_type':   "selectmultiple",
                'name':         "Forum IDs",
                'description':  "The forum ids from which forums the posts should be displayed on the portal.",
                'extra': {"choices": available_forums, "coerce": int}
            }),
        ),
    }),
)


class PortalPlugin(FlaskBBPlugin):

    name = "Portal Plugin"

    description = ("This Plugin provides a simple portal for FlaskBB.")

    author = "sh4nks"

    license = "BSD"

    version = __version__

    settings_key = 'plugin_portal'

    def setup(self):
        self.register_blueprint(portal, url_prefix="/portal")
        connect_event("before-first-navigation-element", inject_portal_link)

    def install(self):
        create_settings_from_fixture(fixture)

    def uninstall(self):
        delete_settings_from_fixture(fixture)

metabomatch/templates/forum/category.html
{% set page_title = category.title %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}
{% block content %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li class="active">{{ category.title }}</li>
</ol>

{% include theme("forum/category_layout.html") %}

{% endblock %}

metabomatch/templates/forum/forum.html
{% set page_title = forum.title %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}
{% block content %}
{% from theme('macros.html') import render_pagination, topic_pages %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li><a href="{{ forum.category.url }}">{{ forum.category.title }}</a></li>
    <li class="active">{{ forum.title }}</li>
</ol>

<div class="pull-left" style="padding-bottom: 10px">
    {{ render_pagination(topics, forum.url) }}
</div> <!-- end span pagination -->

{% if current_user|post_topic(forum) %}
<div class="pull-right" style="padding-bottom: 10px">
    <div class="btn-group">
        <a href="{{ url_for('forum.markread', forum_id=forum.id, slug=forum.slug) }}" class="btn btn-default">
            <span class="fa fa-check"></span> Mark as Read
        </a>

        {% if forum.locked %}
        <span class="btn btn-primary">
            <span class="fa fa-lock"></span> Locked
        </span>
        {% else %}
        <a href="{{ url_for('forum.new_topic', forum_id=forum.id, slug=forum.slug) }}" class="btn btn-primary">
            <span class="fa fa-pencil"></span> New Topic
        </a>
        {% endif %}

    </div>
</div>
{% endif %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="5">
                {{ forum.title }}
            </th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="2">Topic</td>

            <td>Posts</td>

            <td>Views</td>

            <td>Last Post</td>
        </tr>

        {% for topic, topicread in topics.items %}
        <tr>
            <td width="4%" style="vertical-align: middle; text-align: center;">
            {% if topic.locked %}
                <span class="fa fa-lock" style="font-size: 2em"></span>
            {% else %}
                {% if topic|topic_is_unread(topicread, current_user, forumsread) %}
                    <span class="fa fa-comment" style="font-size: 2em"></span>
                {% else %}
                    <span class="fa fa-comment-o" style="font-size: 2em"></span>
                {% endif %}
            {% endif %}

            </td>
            <td>
                <div>
                    <a href="{{ topic.url }}">{{ topic.title }}</a>
                    <!-- Topic Pagination -->
                    {{ topic_pages(topic, flaskbb_config["POSTS_PER_PAGE"]) }}
                    <br />
                    {% if topic.user_id %}
                    <small>by <a href="{{ topic.user.url }}">{{ topic.user.username }}</a></small>
                    {% else %}
                    <small>by {{ topic.username }}</small>
                    {% endif %}
                </div>
            </td>
            <td>
                {{ topic.post_count }}
            </td>
            <td>
                {{ topic.views }}
            </td>
            <td>
                <a href="{{ topic.last_post.url }}">{{ topic.last_post.date_created|time_since }}</a><br />

                {% if topic.last_post.user_id %}
                <small>by <a href="{{ topic.last_post.user.url }}">{{ topic.last_post.user.username }}</a></small>
                {% else %}
                <small>{{ topic.last_post.username }}</small>
                {% endif %}
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="5">
                No Topics so far.
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

{% endblock %}

metabomatch/templates/forum/index.html
{% extends theme("layout.html") %}

{% block title %}
    Software forums - Metabomatch
{% endblock %}

{% block keywords %}
    <meta name="keywords" content="metabomatch, forums, softwares, topic, answer">
    <meta name="description" content="List of our forums dedicated to metabolomics software.">
{% endblock %}

{% block content %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forums</a></li>
</ol>

<ul class="list-group">

{% for category, forums in categories %}
{#    {% include theme("forum/category_layout.html") %}#}
    <li class="list-group-item">
                {% set post_count = forums|map('first')|sum(attribute='post_count') %}
        <div class="container" style="width: 100%">
            <div class="row">
                <div class="col-sm-9">
                    <a href="{{ category.url }}">
                        <strong>{{ category.title }}</strong>
                    </a>
                    {% if post_count %}
                        {% set last_post = forums|map('first')|map(attribute='last_post')|reject('none')|sort(attribute='date_created')|first %}
                        , last post by
                        <a href="{{ url_for('user.profile', username=last_post.username) }}">
                            {% if last_post.user.avatar %}
                                <img src="{{ last_post.user.avatar }}" alt="Avatar" height="20" width="20">
                            {% else %}
                                <img class='img-rounded' src="{{ last_post.user.email | gravatar }}" alt="gravatar"
                                     height="20" width="20" data-toggle="tooltip" data-placement="bottom"
                                     title="{{ last_post.username }}">
                            {% endif %}
                        </a>
                        &bull;  <strong>{{ last_post.date_created | time_since }}</strong>
                    {% endif %}
                </div>
                <div class="col-sm-3 text-right">
                    <span class="text-right">#post <span class="badge"> {{ post_count }}</span> </span>
                </div>
            </div>
        </div>
    </li>
{% endfor %}
</ul>

<!-- Forum Stats -->
<table class="table table-bordered">
    <thead>
        <tr>
            <td colspan="2">
                <strong>Board Statistics</strong>
                [<a href="{{ url_for('forum.who_is_online') }}" onclick="window.open(this.href, 'wio_window','width=500,height=500'); return false;">Who is online?</a>]
            </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                Total number of registered users: <strong>{{ user_count }}</strong> <br />
                Total number of topics: <strong>{{ topic_count }}</strong> <br />
                Total number of posts: <strong>{{ post_count }}</strong> <br />
            </td>
            <td>
                Newest registered user: {% if newest_user %}<a href="{{ newest_user.url }}">{{ newest_user.username }}</a>{% else %}No users{% endif %}<br />
                Registered users online: <strong>{{ online_users }}</strong> <br />
                {% if config["REDIS_ENABLED"] %}
                Guests online: <strong>{{ online_guests }}</strong> <br />
                {% endif %}
            </td>
        </tr>

    </tbody>
</table>

{% endblock %}

metabomatch/templates/forum/memberlist.html
{% set page_title = "Memberlist" %}

{% extends theme("layout.html") %}
{% block content %}
{% from theme('macros.html') import render_pagination, group_field %}

<ul class="breadcrumb">
    <li><a href="{{ url_for('forum.index') }}">Forum</a></li>
    <li class="active">Memberlist</li>
</ul>

<div class="pull-left" style="padding-bottom: 10px">
    {{ render_pagination(users, url_for('forum.memberlist')) }}
</div><!-- /.col-pull-left -->
<div class="pull-right" style="padding-bottom: 10px">
  <form role="form" method="post">
      <div class="input-group">
          {{ search_form.hidden_tag() }}
          {{ group_field(search_form.search_query) }}
          <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">Search</button>
          </span>
      </div>
  </form>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Posts</th>
            <th>Date registered</th>
            <th>Group</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users.items %}
        <tr>
            <td>{{ user.id }}</td>
            <td><a href="{{ user.url }}">{{ user.username }}</a></td>
            <td>{{ user.post_count }}</td>
            <td>{{ user.date_joined|format_date('%b %d %Y') }}</td>
            <td>{{ user.primary_group.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

metabomatch/templates/forum/new_post.html
{% set page_title = _("New Post") %}
{% set active_forum_nav=True %}

{% extends theme("layout.html") %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-markdown.min.css') }}">
{% endblock %}

{% block content %}
{% from theme("macros.html") import render_field_2, render_submit_field %}

{#<ul class="breadcrumb">#}
{#    <li><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>#}
{#    <li><a href="{{ topic.forum.url }}">{{ topic.forum.title }}</a></li>#}
{#    <li><a href="{{ topic.url }}">{{ topic.title }} </a></li>#}
{#    <li class="active">{% trans %}New Post{% endtrans %}</li>#}
{#</ul>#}

<form class="form" role="form" method="post">
    {{ form.hidden_tag() }}
    <h3>{% trans %}New Post{% endtrans %}</h3>
    <hr/>
    {% if preview %}
    <div class="form-group">
        <div class="col-sm-12">
            <label>{% trans %}Preview{% endtrans %}</label>
            <div class="form-control preview-body">
                {% autoescape false %}
                {{ preview|markup }}
                {% endautoescape %}
            </div>
        </div>
    </div>
    {% endif %}

    {{ render_field_2(form.content, div_class="col-sm-12", rows="12", placeholder="", **{'data-provide': 'markdown', 'data-autofocus': 'true', 'id': 'quickreply-editor'}) }}
    <div class="col-sm-12" style="padding-top: 5px">
        {{ render_submit_field(form.submit) }}
    </div>
</form>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/marked.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-markdown.js') }}"></script>
{% endblock %}

metabomatch/templates/forum/topic_controls.html
<div class="pull-left" style="padding-bottom: 10px">
    {{ render_pagination(posts, topic.url) }}
</div> <!-- end span pagination -->

<div class="pull-right" style="padding-bottom: 10px">
    <div class="btn btn-group">
        {% if current_user|delete_topic(topic.first_post.user_id, topic.forum) %}
        <a href="{{ url_for('forum.delete_topic', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-danger">
            <span class="fa fa-trash-o"></span> Delete Topic
        </a>
        {% endif %}
        {% if current_user|can_moderate(topic.forum) %}
        {% if not topic.locked %}
        <a href="{{ url_for('forum.lock_topic', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-warning">
            <span class="fa fa-lock"></span> Lock Topic
        </a>
        {% else %}
        <a href="{{ url_for('forum.unlock_topic', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-warning">
            <span class="fa fa-unlock"></span> Unlock Topic
        </a>
        {% endif %}
        {% endif %}
    </div>

    {% if current_user.is_authenticated() %}
    <div class="btn btn-group">
        {% if current_user.is_tracking_topic(topic) %}
        <a href="{{ url_for('forum.untrack_topic', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-default"><span class="fa fa-star">
            </span> Untrack Topic
        </a>
        {% else %}
        <a href="{{ url_for('forum.track_topic', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-default">
            <span class="fa fa-star"></span> Track Topic
        </a>
        {% endif %}

        {% if current_user|post_reply(topic.forum) and not (topic.locked or topic.forum.locked) %}
        <a href="{{ url_for('forum.new_post', topic_id=topic.id, slug=topic.slug) }}" class="btn btn-primary">
            <span class="fa fa-pencil"></span> Reply
        </a>
        {% endif %}
    </div>
    {% endif %}
</div>

<div class="clearfix"></div>