metabomatch/user/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.user.views
    ~~~~~~~~~~~~~~~~~~~~

    The user view handles the user profile
    and the user settings from a signed in user.

    :copyright: (c) 2014 by the FlaskBB Team.
    :license: BSD, see LICENSE for more details.
"""
from datetime import datetime
import os

from flask import Blueprint, flash, request, redirect, url_for
from flask.ext.login import login_required, current_user
from flask.ext.themes2 import get_themes_list

from metabomatch.extensions import db
from metabomatch.flaskbb.utils.helpers import render_template

try:
    from metabomatch.private_keys import GUEST_USER_ID
except ImportError:
    GUEST_USER_ID = os.environ.get('GUEST_USER_ID')

try:
    from metabomatch.private_keys import TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET
except ImportError:
    TWITTER_CONSUMER_SECRET = os.environ.get('TWITTER_CONSUMER_SECRET')
    TWITTER_CONSUMER_KEY = os.environ.get('TWITTER_CONSUMER_KEY')

from metabomatch.user.models import User, PrivateMessage
from metabomatch.user.forms import (ChangePasswordForm, ChangeEmailForm,
                                    ChangeUserDetailsForm, GeneralSettingsForm,
                                    NewMessageForm, EditMessageForm)
from metabomatch.twitter_api import UserClient


user = Blueprint("user", __name__, template_folder="templates")


@user.route("/<username>")
def profile(username):
    user_inst = User.query.filter_by(username=username).first_or_404()
    # if username == 'Guest':  # user.id == GUEST_USER_ID or
    #     return render_template('errors/forbidden_page.html')

    if user_inst.twitter_access_token and user_inst.twitter_secret_token:
        client = UserClient(TWITTER_CONSUMER_KEY,
                            TWITTER_CONSUMER_SECRET,
                            user_inst.twitter_access_token,
                            user_inst.twitter_secret_token)
        # fetching image url
        response = client.api.users.show.get(screen_name=username)
        user_inst.profile_image_url = response.data['profile_image_url'].replace('normal', '400x400')
    return render_template("user/profile.html", user=user_inst, guest_id=GUEST_USER_ID)


@user.route("/<username>/topics")
def view_all_topics(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    topics = user.all_topics(page)
    return render_template("user/all_topics.html", user=user, topics=topics)


@user.route("/<username>/posts")
def view_all_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.all_posts(page)
    return render_template("user/all_posts.html", user=user, posts=posts)


@user.route("/settings/general", methods=["POST", "GET"])
@login_required
def settings():
    form = GeneralSettingsForm()

    form.theme.choices = [(theme.identifier, theme.name)
                          for theme in get_themes_list()]

    if form.validate_on_submit():
        current_user.theme = form.theme.data
        current_user.save()

        flash("Your settings have been updated!", "success")
    else:
        form.theme.data = current_user.theme

    return render_template("user/general_settings.html", form=form)


@user.route("/settings/password", methods=["POST", "GET"])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        current_user.save()

        flash("Your password have been updated!", "success")
    return render_template("user/change_password.html", form=form)


@user.route("/settings/email", methods=["POST", "GET"])
@login_required
def change_email():
    form = ChangeEmailForm(current_user)
    if form.validate_on_submit():
        current_user.email = form.new_email.data
        current_user.save()

        flash("Your email have been updated!", "success")
    return render_template("user/change_email.html", form=form)


@user.route("/settings/user-details", methods=["POST", "GET"])
@login_required
def change_user_details():
    form = ChangeUserDetailsForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()

        flash("Your details have been updated!", "success")

    return render_template("user/change_user_details.html", form=form)


@user.route("/messages")
@user.route("/messages/inbox")
@login_required
def inbox():
    messages = PrivateMessage.query.filter(
        PrivateMessage.user_id == current_user.id,
        PrivateMessage.draft == False,
        PrivateMessage.trash == False,
        db.not_(PrivateMessage.from_user_id == current_user.id)).all()
    return render_template("message/inbox.html", messages=messages)


@user.route("/messages/<int:message_id>/view")
@login_required
def view_message(message_id):
    message = PrivateMessage.query.filter_by(id=message_id).first()
    if message.unread:
        message.unread = False
        db.session.commit()
    return render_template("message/view_message.html", message=message)


@user.route("/messages/sent")
@login_required
def sent():
    messages = PrivateMessage.query.filter(
        PrivateMessage.user_id == current_user.id,
        PrivateMessage.draft == False,
        PrivateMessage.trash == False,
        db.not_(PrivateMessage.to_user_id == current_user.id)).all()
    return render_template("message/sent.html", messages=messages)


@user.route("/messages/trash")
@login_required
def trash():
    messages = PrivateMessage.query.filter(
        PrivateMessage.user_id == current_user.id,
        PrivateMessage.trash == True).all()
    return render_template("message/trash.html", messages=messages)


@user.route("/messages/draft")
@login_required
def drafts():
    messages = PrivateMessage.query.filter(
        PrivateMessage.user_id == current_user.id,
        PrivateMessage.draft == True,
        PrivateMessage.trash == False).all()
    return render_template("message/drafts.html", messages=messages)


@user.route("/messages/new", methods=["POST", "GET"])
@login_required
def new_message():
    form = NewMessageForm()
    to_user = request.args.get("to_user")

    if request.method == "POST":
        if "save_message" in request.form:
            to_user = User.query.filter_by(username=form.to_user.data).first()

            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False,
                      as_draft=True)

            flash("Message saved!", "success")
            return redirect(url_for("user.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()

            # Save the message in the current users inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=current_user.id,
                      unread=False)

            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True)

            flash("Message sent!", "success")
            return redirect(url_for("user.sent"))
    else:
        form.to_user.data = to_user

    return render_template("message/message_form.html", form=form,
                           title="Compose Message")


@user.route("/messages/<int:message_id>/edit", methods=["POST", "GET"])
@login_required
def edit_message(message_id):
    message = PrivateMessage.query.filter_by(id=message_id).first_or_404()

    if not message.draft:
        flash("You cannot edit a sent message", "danger")
        return redirect(url_for("user.inbox"))

    form = EditMessageForm()

    if request.method == "POST":
        if "save_message" in request.form:
            to_user = User.query.filter_by(username=form.to_user.data).first()

            # Move the message from ``Drafts`` to ``Sent``.
            message.draft = False
            message.to_user = to_user.id
            message.save()

            flash("Message saved!", "success")
            return redirect(url_for("user.drafts"))

        if "send_message" in request.form and form.validate():
            to_user = User.query.filter_by(username=form.to_user.data).first()
            # Save the message in the recievers inbox
            form.save(from_user=current_user.id,
                      to_user=to_user.id,
                      user_id=to_user.id,
                      unread=True)

            # Move the message from ``Drafts`` to ``Sent``.
            message.draft = False
            message.to_user = to_user
            message.date_created = datetime.utcnow()
            message.save()

            flash("Message sent!", "success")
            return redirect(url_for("user.sent"))
    else:
        form.to_user.data = message.to_user.username
        form.subject.data = message.subject
        form.message.data = message.message

    return render_template("message/message_form.html", form=form,
                           title="Edit Message")


@user.route("/messages/<int:message_id>/move")
@login_required
def move_message(message_id):
    message = PrivateMessage.query.filter_by(id=message_id).first_or_404()
    message.trash = True
    message.save()
    flash("Message moved to Trash!", "success")
    return redirect(url_for("user.inbox"))


@user.route("/messages/<int:message_id>/restore")
@login_required
def restore_message(message_id):
    message = PrivateMessage.query.filter_by(id=message_id).first_or_404()
    message.trash = False
    message.save()
    flash("Message restored from Trash!", "success")
    return redirect(url_for("user.inbox"))


@user.route("/messages/<int:message_id>/delete")

metabomatch/flaskbb/themes/bootstrap3/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
        {% block title %}
            {%- if not page_title -%}
                {{ flaskbb_config["PROJECT_TITLE"] }} - {{ flaskbb_config["PROJECT_SUBTITLE"] }}
            {%- else -%}
                {{ page_title }} - {{ flaskbb_config["PROJECT_TITLE"] }}
            {%- endif -%}
        {% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="FlaskBB is a forum software written in Flask">
        <meta name="author" content="FlaskBB Team">

        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

        {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/code.css') }}">
        <link rel="stylesheet" href="{{ theme_static('css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ theme_static('css/font-awesome.min.css') }}">
        <link rel="stylesheet" href="{{ theme_static('css/flaskbb.css') }}">
        {% endblock %}
    </head>

    <body>
        <div id="wrap">
        {% block navigation %}
        {%- from "macros.html" import topnav with context -%}
        <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">FlaskBB</a>
                    </div>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            {{ emit_event("before-first-navigation-element") | safe }}

                            {# active_forum_nav is set in {forum, category, topic}.html and new_{topic, post}.html #}
                            {{ topnav(endpoint='forum.index', name='Forum', icon='fa fa-comment', active=active_forum_nav) }}
                            {{ topnav(endpoint='forum.memberlist', name='Memberlist', icon='fa fa-user') }}
                            {{ topnav(endpoint='forum.search', name='Search', icon='fa fa-search') }}

                            {{ emit_event("after-last-navigation-element") | safe }}
                        </ul>

                    {% if current_user and current_user.is_authenticated() %}
                        <div class="btn-group navbar-btn navbar-right" style="padding-left: 15px; margin-right: -10px">
                            <a class="btn btn-primary" href="{{ url_for('user.profile', username=current_user.username) }}">
                                <span class="fa fa-user"></span> {{ current_user.username }}
                            </a>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('forum.topictracker') }}"><span class="fa fa-book"></span> Topic Tracker</a></li>
                                <li class="divider"></li>

                                <li><a href="{{ url_for('user.settings') }}"><span class="fa fa-cogs"></span> Settings</a></li>
                                {% if current_user|is_admin_or_moderator %}
                                <li><a href="{{ url_for('management.overview') }}"><span class="fa fa-cog"></span> Management</a></li>
                                <li class="divider"></li>
                                {% endif %}

                                <li><a href="{{ url_for('auth.logout') }}"><span class="fa fa-power-off"></span> Logout</a></li>
                            </ul>
                        </div>

                        <div class="btn-group navbar-btn navbar-right">
                            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                                <span class="fa fa-envelope"></span> <span class="badge">{{ current_user.pm_unread }}</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('user.inbox') }}"><span class="fa fa-envelope"></span> Inbox</a></li>
                                <li><a href="{{ url_for('user.new_message') }}"><span class="fa fa-pencil"></span> New Message</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <div class="btn-group navbar-btn navbar-right">
                            <a class="btn btn-primary" href="{{ url_for('auth.login') }}">
                                <span class="fa fa-user"></span> Login
                            </a>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                                <li><a href="{{ url_for('auth.forgot_password') }}">Reset Password</a></li>
                            </ul>
                        </div>
                    {% endif %}
                    </div><!-- nav-collapse -->
                </div><!-- container -->
            </nav> <!-- navbar navbar-inverse -->
            {% endblock %}


            <div class="container">
                {% block messages %}
                    {% include 'flashed_messages.html' %}
                {% endblock %}

                {% block content %}
                {% endblock %}
            </div> <!-- /container -->
        </div> <!-- End wrap -->

            {% block footer %}
            <div id="footer">
                <div class="container">
                    <p class="text-muted credit pull-left">powered by <a href="http://flask.pocoo.org">Flask</a></p>
                    <p class="text-muted credit pull-right">&copy; 2013 - <a href="http://flaskbb.org">FlaskBB.org</a></p>
                </div>
            </div>
            {% endblock %}

        {% block javascript %}
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {% endblock %}

        {% block scripts %}
        {% endblock %}
    </body>
</html>